let professors = [
    ["https://i.imgur.com/dCGtWzT.jpg/Vishnu", "Vishunu ", 0],
    ["https://i.imgur.com/bM15nvf.jpg/Proadpran", "Proadpran", 1],
    ["https://i.imgur.com/OYmb6zj.jpg/Nuttapong", "Nuttapong", 2],
    ["https://i.imgur.com/3cDSe4H.jpg/Yachai", "Yachai", 3],
    ["https://i.imgur.com/hplfH1T.jpg/Wiwat", "Wiwat", 4],
    ["https://i.imgur.com/EqGtaAr.jpg/Twittie", "Twittie", 5],
    ["https://i.imgur.com/axcrYCk.jpg/Peerapon", "Peerapon", 6],
    ["https://i.imgur.com/Ex4XFRu.jpg/Veera", "Veera", 7],
    ["https://i.imgur.com/jl4Z1Wv.jpg/Sukree", "Sukree", 8],
    ["https://i.imgur.com/N3xZ1Cb.jpg/Prabhas", "Prabhas", 9],
    ["https://i.imgur.com/Tu6CqgD.jpg/Chate", "Chate", 10],
    ["https://i.imgur.com/Z0uv9Kj.jpg/Nattee", "Nattee", 11],
    ["https://i.imgur.com/o3uY18N.jpg/Pizzanu", "Pizzanu", 12],
    ["https://i.imgur.com/rAzZ49e.jpg/Boonserm", "Boonserm", 13],
    ["https://i.imgur.com/nrLSPWW.jpg/Jessada", "Jessada", 14],
    ["https://i.imgur.com/1iL55SK.jpg/Krerk", "Krerk", 15],
    ["https://i.imgur.com/OjeymTc.jpg/Nuengwong", "Nuengwong", 16],
    ["https://i.imgur.com/a189BPe.jpg/Taratip", "Taratip", 17],
    ["https://i.imgur.com/jxVvywT.jpg/Thanarat", "Thanarat", 18],
    ["https://i.imgur.com/B3BPsh9.jpg/Duangdao", "Duangdao", 19],
    ["https://i.imgur.com/lg46STE.jpg/Narongdech", "Narongdech", 20],
    ["https://i.imgur.com/8AgZuRh.jpg/Ekapol", "Ekapol", 21],
    ["https://i.imgur.com/Rbfhs2n.jpg/Chotirat", "Chotirat", 22],
    ["https://i.imgur.com/WThF9Dk.jpg/Pitchaya", "Pitchaya", 23],
    ["https://i.imgur.com/ZmJmqoq.jpg/Thongchai", "Thongchai", 24],
    ["https://i.imgur.com/9JQ6wjx.jpg/Pittipol", "Pittipol", 25],
    ["https://i.imgur.com/JSxRKCl.jpg/Atiwong", "Atiwong", 26],
    ["https://i.imgur.com/FgvnGHn.jpg/Punnarai", "Punnarai", 27],
    ["https://i.imgur.com/B6Zt6eC.jpg/Natawut", "Natawut", 28],
    ["https://i.imgur.com/96Pzecu.jpg/Kultida", "Kultida", 29],
    ["https://i.imgur.com/hrOqXfU.jpg/Setha", "Setha", 30],
    ["https://i.imgur.com/gbiso76.jpg/Atthawith", "Atthawith", 31],
    ["https://i.imgur.com/acddUE1.jpg/Nakornthip", "Nakornthip", 32],
    ["https://i.imgur.com/e6fu41o.jpg/Athasit", "Athasit", 33],
    ["https://i.imgur.com/O8cVZS5.jpg/Arthit", "Arthit", 34]
]